export {
  authenticateFaculty,
  authenticateTeam,
  getProjects,
  getAvailableProjects,
  getProjectById,
  createProject,
  updateProject,
  deleteProject,
  getTeams,
  updateTeam,
  getAllocations,
  getAllocationDetails,
  createAllocation,
  hasActiveAllocationForProject,
  getAllocatedProjectIds,
} from './api';
